name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}"/scrapyd:latest

  push:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Push the Docker image
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push "${{ secrets.DOCKER_USERNAME }}"/scrapyd:latest
